-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CustomersApi.Object.Building exposing (..)

import CustomersApi.InputObject
import CustomersApi.Interface
import CustomersApi.Object
import CustomersApi.Scalar
import CustomersApi.ScalarCodecs
import CustomersApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int CustomersApi.Object.Building
id =
    Object.selectionForField "Int" "id" [] Decode.int


label : SelectionSet String CustomersApi.Object.Building
label =
    Object.selectionForField "String" "label" [] Decode.string


position :
    SelectionSet decodesTo CustomersApi.Object.Position
    -> SelectionSet (Maybe decodesTo) CustomersApi.Object.Building
position object____ =
    Object.selectionForCompositeField "position" [] object____ (Basics.identity >> Decode.nullable)


site :
    SelectionSet decodesTo CustomersApi.Object.Site
    -> SelectionSet decodesTo CustomersApi.Object.Building
site object____ =
    Object.selectionForCompositeField "site" [] object____ Basics.identity
