-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CustomersApi.Object.Position exposing (..)

import CustomersApi.InputObject
import CustomersApi.Interface
import CustomersApi.Object
import CustomersApi.Scalar
import CustomersApi.ScalarCodecs
import CustomersApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


long : SelectionSet CustomersApi.ScalarCodecs.Decimal CustomersApi.Object.Position
long =
    Object.selectionForField "ScalarCodecs.Decimal" "long" [] (CustomersApi.ScalarCodecs.codecs |> CustomersApi.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)


lat : SelectionSet CustomersApi.ScalarCodecs.Decimal CustomersApi.Object.Position
lat =
    Object.selectionForField "ScalarCodecs.Decimal" "lat" [] (CustomersApi.ScalarCodecs.codecs |> CustomersApi.Scalar.unwrapCodecs |> .codecDecimal |> .decoder)
