-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CustomersApi.Object.Site exposing (..)

import CustomersApi.InputObject
import CustomersApi.Interface
import CustomersApi.Object
import CustomersApi.Scalar
import CustomersApi.ScalarCodecs
import CustomersApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int CustomersApi.Object.Site
id =
    Object.selectionForField "Int" "id" [] Decode.int


label : SelectionSet String CustomersApi.Object.Site
label =
    Object.selectionForField "String" "label" [] Decode.string


area :
    SelectionSet decodesTo CustomersApi.Object.Area
    -> SelectionSet (Maybe decodesTo) CustomersApi.Object.Site
area object____ =
    Object.selectionForCompositeField "area" [] object____ (Basics.identity >> Decode.nullable)


address : SelectionSet (Maybe (List String)) CustomersApi.Object.Site
address =
    Object.selectionForField "(Maybe (List String))" "address" [] (Decode.string |> Decode.list |> Decode.nullable)


zipCode : SelectionSet (Maybe String) CustomersApi.Object.Site
zipCode =
    Object.selectionForField "(Maybe String)" "zipCode" [] (Decode.string |> Decode.nullable)


city : SelectionSet (Maybe String) CustomersApi.Object.Site
city =
    Object.selectionForField "(Maybe String)" "city" [] (Decode.string |> Decode.nullable)


owner :
    SelectionSet decodesTo CustomersApi.Object.Customer
    -> SelectionSet decodesTo CustomersApi.Object.Site
owner object____ =
    Object.selectionForCompositeField "owner" [] object____ Basics.identity
