-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CustomersApi.Object exposing (..)


type Area
    = Area


type Building
    = Building


type Customer
    = Customer


type Position
    = Position


type Site
    = Site
