-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CustomersApi.ScalarCodecs exposing (..)

import CustomersApi.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Decimal =
    CustomersApi.Scalar.Decimal


type alias Void =
    CustomersApi.Scalar.Void


codecs : CustomersApi.Scalar.Codecs Decimal Void
codecs =
    CustomersApi.Scalar.defineCodecs
        { codecDecimal = defaultCodecs.codecDecimal
        , codecVoid = defaultCodecs.codecVoid
        }
